// <auto-generated />
using GalFingerPrint.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GalFingerPrint.Server.Migrations
{
    [DbContext(typeof(GalDbContext))]
    [Migration("20251024161405_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GalFingerPrint.Server.Models.Galgame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("VndbId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("VndbId")
                        .IsUnique();

                    b.ToTable("Galgames");
                });

            modelBuilder.Entity("GalFingerPrint.Server.Models.GalgameHash", b =>
                {
                    b.Property<int>("HashId")
                        .HasColumnType("integer");

                    b.Property<int>("GalgameId")
                        .HasColumnType("integer");

                    b.Property<int>("Cnt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("HashId", "GalgameId");

                    b.HasIndex("GalgameId");

                    b.ToTable("GalgameHashes");
                });

            modelBuilder.Entity("GalFingerPrint.Server.Models.Hash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HashValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HashValue")
                        .IsUnique();

                    b.ToTable("Hashes");
                });

            modelBuilder.Entity("GalFingerPrint.Server.Models.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Address")
                        .HasColumnType("bigint");

                    b.Property<string>("Hashes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("VndbId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Address", "VndbId")
                        .IsUnique();

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("GalFingerPrint.Server.Models.GalgameHash", b =>
                {
                    b.HasOne("GalFingerPrint.Server.Models.Galgame", null)
                        .WithMany("GalgameHashes")
                        .HasForeignKey("GalgameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GalFingerPrint.Server.Models.Hash", null)
                        .WithMany("GalgameHashes")
                        .HasForeignKey("HashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GalFingerPrint.Server.Models.Galgame", b =>
                {
                    b.Navigation("GalgameHashes");
                });

            modelBuilder.Entity("GalFingerPrint.Server.Models.Hash", b =>
                {
                    b.Navigation("GalgameHashes");
                });
#pragma warning restore 612, 618
        }
    }
}
