name: Generate OpenAPI Artifact

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  openapi:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: galfingerprint
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=5
    env:
      DB_CONNECTION_STRING: Host=postgres;Port=5432;Database=galfingerprint;Username=postgres;Password=postgres
      ASPNETCORE_ENVIRONMENT: Development
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build GalFingerPrint.Server/GalFingerPrint.Server.csproj --configuration Release --no-restore

      - name: Install Swagger CLI
        run: dotnet tool install --tool-path ./.dotnet-tools Swashbuckle.AspNetCore.Cli --version 6.6.2

      - name: Generate OpenAPI document
        run: ./.dotnet-tools/swagger tofile --output GalFingerPrint.Server/openapi.json GalFingerPrint.Server/bin/Release/net8.0/GalFingerPrint.Server.dll v1

      - name: Upload OpenAPI artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi-spec
          path: GalFingerPrint.Server/openapi.json
